# ============================================================
# Liquibase Properties - Configuración de conexión
# ============================================================
changeLogFile=changelog/db.changelog-master.yaml
url=jdbc:postgresql://localhost:5437/Bd_exercise_api
username=postgres
password=camilo200804
driver=org.postgresql.Driver
liquibase.hub.mode=off
